chore: comment out debugging steps and update docker-compose source path

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -21,17 +21,17 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v5
-      - name: Debug backend files
-        run: |
-          echo "Current workspace:"
-          pwd
-          echo "Backend directory contents:"
-          ls -R ./backend || echo "Backend folder not found!"
-      - name: Debug file tree
-        run: |
-          echo "📂 Current workspace:"
-          pwd
-          ls -R .
+#      - name: Debug backend files
+#        run: |
+#          echo "Current workspace:"
+#          pwd
+#          echo "Backend directory contents:"
+#          ls -R ./backend || echo "Backend folder not found!"
+#      - name: Debug file tree
+#        run: |
+#          echo "📂 Current workspace:"
+#          pwd
+#          ls -R .
       - name: Upload compose to server
         uses: appleboy/scp-action@v1
         with:
@@ -39,7 +39,7 @@ jobs:
           username: ${{ secrets.SSH_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: ${{ secrets.SSH_PORT }}
-          source: "./backend/docker-compose.prod.yml"
+          source: "./docker-compose.prod.yml"
           target: "${{ secrets.DEPLOY_PATH || '~/src/btl_oop_ptit' }}/"
       - name: Deploy to server via SSH
         uses: appleboy/ssh-action@v1.0.3
